name: Format Codebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Setup ruff
        run: uv tool install ruff@latest

      - name: Format code with uv
        run: ruff format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "style: codebase with ruff"
          branch: ${{ github.head_ref }}
