name: Validate & Test UGF Project

on:
  push:
    paths:
      - 'data/**'
      - 'src/**'
      - 'test/**'
      - '.github/workflows/validate.yml'
  pull_request:
    paths:
      - 'data/**'
      - 'src/**'
      - 'test/**'
      - '.github/workflows/validate.yml'

permissions:
  contents: read

jobs:
  run-unit-tests:
    name: Run Pytest (Unit Tests)
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pytest
        run: python -m pytest

  validate-data:
    name: Validate YAML Data (Integration Test)
    runs-on: ubuntu-latest
    needs: run-unit-tests
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run UGF Validator
        working-directory: ./src
        run: python validator.py
